version: '3.1'

services:
    db:
        container_name: db
        image: mariadb
        restart: always
        command: --max_allowed_packet=256M
        volumes:
            - "./data/db:/var/lib/mysql:delegated"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}