version: '3.1'

services:
    dozzle:
        container_name: dozzle
        image: amir20/dozzle:latest
        restart: always
        ports:
            - 8888:8080
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin:latest
        restart: always
        ports:
            - 8080:80
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=db
            - PMA_PORT=3306
            - PMA_USER=${MYSQL_USER}
            - PMA_PASSWORD=${MYSQL_PASSWORD}
            - PMA_PMADB=phpmyadmin
            - PMA_CONTROLUSER=root
            - PMA_CONTROLPASS=${MYSQL_ROOT_PASSWORD}
        depends_on:
            - db
    db:
        container_name: db
        image: mariadb
        restart: always
        command: --max_allowed_packet=256M
        volumes:
            - "./data/db:/var/lib/mysql:delegated"
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}